### ISSUE TITLE
Erreur renvoyée (prgm Python)

### ISSUE THREAD

**Issue by MaximePrince** [guirem/plugin-googlecast#1]
Lors de l'utilisation du plugin, ce dernier me renvoie ceci dans les logs. Je pense qu'il doit y avoir un problème.

`SyntaxError: invalid syntax
  File "/var/www/html/plugins/googlecast/resources/googlecast.py", line 480
    return ret[1:]
         ^`

Merci d'avance,
MaximePrince

**Comment by guirem** [comment]
Un typo de dernière minute, J'ai mis à jour.
