### ISSUE TITLE
Erreur à installation des dépendances 'zeroconf'

### ISSUE THREAD

**Issue by IzeNogoud** [guirem/plugin-googlecast#40]
## Description

Lors de l'installation des dépendances, une erreur se produit lors de l'installation du package 'zeroconf'.

## Etapes à reproduire

1. Installer les dépendances

## Contexte:

Version de python : Python 3.4.2
Version de pip : pip 1.5.6

Echec également lors de l'installation manuelle avec pip3.

sudo pip3 install zeroconf>=0.17.7

`Downloading/unpacking zeroconf
  Downloading zeroconf-0.21.3-py2.py3-none-any.whl
Downloading/unpacking ifaddr (from zeroconf)
  Downloading ifaddr-0.1.5.tar.gz
  Running setup.py (path:/tmp/pip-build-8skfp23v/ifaddr/setup.py) egg_info for package ifaddr
    error in ifaddr setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in ifaddr setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers`

## Environnement:

* **Version Jeedom**: v3.2.11
* **Plateforme**: Smartjeedom (odroid)
* **Version du Plugin**: 2018-10-16 21:06:51

**Comment by guirem** [comment]
Probablement lié à maj de ifaddr fin novembre. J'ai ouvert un ticket sur le projet en question https://github.com/pydron/ifaddr/issues/14

En attendant, tu peux tenter ces commandes (les tester une par une en retentant l'installation des dépendances):

- sudo python3 -m pip install --upgrade setuptools
- sudo apt-get install python3-setuptools

**Comment by IzeNogoud** [comment]
Cela a fonctionné en lançant la première ligne de commande que tu as fourni (avec pip).

Merci pour ta réactivité.
