### ISSUE TITLE
Le scan ne trouve rien

### ISSUE THREAD

**Issue by Koumal** [guirem/plugin-googlecast#43]
Bonjour,

Tout d'abord, merci à Guirem pour ce super plugin. Je l'utilise depuis des mois et il est parfait.
Mon problème est survenu à la suite de mon changement de box. J'avais une freebox v6 et tout fonctionnait à merveille. Et j'ai décidé de monter une box 4g sur un raspberry, parce que la Freebox me coûtait cher pour pas grand chose vu mon débit de 8mo. Enfin peu importe.
J'ai donc maintenant une box 4g sur un raspberry, le soucis provient (je pense) du fait que j'ai une plage d'IP différente entre le LAN (192.168.2.X) et le WLAN (192.168.1.X). C'est le seul moyen que j'ai trouvé pour faire fonctionner les 2 sur le raspberry. Donc la box Jeedom smart et mes GH mini et chromecast sont bien sur le même réseau, mais pas sur la même plage.
Du coup, j'en arrive au problème de scan, aujourd'hui j'ai supprimé mes appareil GH et chromecast (de mon ancien réseau Freebox sur des IP 192.168.0.X) sur la page du plugin et j'ai relancé le scan.
Et là rien du tout.

Auriez-vous une idée pour me sauver la mise ?

Merci d'avance pour votre aide.

**Comment by guirem** [comment]
Probablement lié à une problème réseau et non lié au plugin.
