### ISSUE TITLE
Télé muted après interactions google mini

### ISSUE THREAD

**Issue by Amaurgit** [guirem/plugin-googlecast#44]
## Description
J'ai 2 devices Gcast chez moi : un google mini et une télé android. Lorsque j'interroge le google mini, la télé est mise en sourdine mais le son ne se remet pas une fois l'interaction avec le google mini terminée.
## Etapes à reproduire (pour les bugs)

1. TV et google mini allumés
2. Interaction avec google mini : "ok google bla bla bla bla"
3. Le son de la TV se coupe
4. L'interaction google mini est terminée mais le son de la TV ne reprend pas

## Contexte:
TV et google mini allumés.

## Environnement:

* **Version Jeedom**: 3.2.12
* **Plateforme**: Raspberry pi 3B+
* **Version du Plugin**: 2018-12-11 23:30:56

Merci du coup de pouce :)

**Comment by guirem** [comment]
Ce n'est pas lié au plugin car les intéractions de type 'ok google' ne passe pas du tout par le plugin
