### ISSUE TITLE
ajout d'application

### ISSUE THREAD

**Issue by etopit** [guirem/plugin-googlecast#45]
hello,
c'est pas tellment un bug mais plus une demande d'information sur une éventuel fonctionnalité.
Alors avant de continuer mes recherches. Est'il possible d'ajouter facilement des applications dans le plugins ? (par application je pense simplement au action possible avec le plugins) par exemple l'application youtube déjà présente ! qui permet de jouer une vidéo youtube.

je pense notamment à l'application molotovTV afin de pouvoir lancer des chaînes TV sur la chromecast, directement via le plugins.

merci pour votre retour et pour votre plugins.

**Comment by guirem** [comment]
Bonsoir,
C'est effectivement assez complexe pour intégrer cela. D'autant plus qu'il est nécessaire de s'authentifier.
Ce n'est donc pas prévu pour le moment.
