### ISSUE TITLE
Changement dans l'API Google.

### ISSUE THREAD

**Issue by mguyard** [guirem/plugin-googlecast#47]
## Description

Google a changé des éléments dans son API.
Tout est décrit ici :

- https://github.com/rithvikvibhu/GHLocalApi/issues/39

- https://gist.github.com/rithvikvibhu/1a0f4937af957ef6a78453e3be482c1f

## Etapes à reproduire (pour les bugs)

L'accès à /setup/eureka_info fonctionne encore (comme indiqué dans le second lien que j'ai mis) sur mes GH Mini mais plus l'accès à l'alarm par exemple (ce qui m'a fait m'en rendre compte car je l'utilise dans mes scénarios) ou d'autres URLs.

## Proposition de solution (optionnel):

- Les solutions sont indiquées ici : https://github.com/rithvikvibhu/GHLocalApi/issues/39
Le plus dure étant de récupérer le token cast-local-authorization-token. Surtout dans un contexte comme celui de Jeedom

## Environnement:

* **Version Jeedom**: Toutes
* **Plateforme**: Toutes
* **Version du Plugin**: Toutes

**Comment by guirem** [comment]
Hi,

It seems there isn't any easy fix/solution for now.
Unfortunately this is not really a bug but more an evolution of Google API that's causing this feature to stop working.

I'll leave this issue open until a suitable solution can be implemented.

**Comment by guirem** [comment]
implemented in version 2.15
