### ISSUE TITLE
Problème Google Cast TTS sur WiFi Raspberry

### ISSUE THREAD

**Issue by JeedHome44** [guirem/plugin-googlecast#63]
Bonjour,

J'ai tous mes GH sur ma Freebox. J'arrive avec Google Cast à faire parler mes GH et j'ai donc inventé le mégaphone ciblé sur Google Home grâce au plugin Google Cast.

Aujourd'hui, je souhaite basculer tous les GH de la maison sur mon réseau 4G car chez moi le débit ADSL est de 7 Mbps alors que la 4G est de 100Mbps. J'ai donc changé le GH de Wifi. Il marche bien.

Mon Raspberry Jeedom est en ethernet sur la Freebox et en Wifi sur la 4G.
J'ai donc vérifié si le plugin Google Cast voyait bien le Google Home en Wifi.  J'ai donc fait une recherche et ca a bien actualisé l'IP.

Problème: je teste de faire parler le GH avec la fonction TTS sur le Dashboard.
Ca change uniquement le volume mais ca ne fait pas parler le GH. J'ai pris une voix haute qualité avec l'API Google.

Je précise que ce Jeedom est toujours en version 3.

**Comment by guirem** [comment]
Quelle configuration as-tu dans le plugin pour 'Utiliser l'adresse Jeedom externe'. Il faut s'assurer que ce soit bien décoché je pense.

**Comment by JeedHome44** [comment]
c'est déjà décoché. je ne pige pas pourquoi ca ne fait pas parler le GH si je le change de LAN mais le plugin le voit bien pourtant.

**Comment by guirem** [comment]
entends tu quelque chose quand tu cliques le bonton 'test' à coté de 'Utiliser l'adresse Jeedom externe' quand tu mets ton pc sur le même réseau que les GH?
