### ISSUE TITLE
Stop Cast Design après 10 minutes

### ISSUE THREAD

**Issue by JeedHome44** [guirem/plugin-googlecast#65]
Bonjour,

Je castais sans problème des design sur mes Google Nest Hub depuis des mois.
Ce matin, quand je cast un Design, il s'arrête de lui même au bout de 10 minutes et sur Jeedom, le statut  est toujours sur "Plan - Jeedom" Je n'ai fait aucune mise à jour hier ou cette nuit.
Serait-ce une mise à jour Google qui empèche de laisser un Design en continu sur Nest Hub maintenant?

**Comment by guirem** [comment]
Issue is probably originating from Google Nest Hub firmware or Dashcast application.
