### ISSUE TITLE
ajout de radio custom

### ISSUE THREAD

**Issue by rudak** [guirem/plugin-googlecast#67]
## Description
Salut, je ne parviens pas a rajouter une radio. je pense avoir fait correctement pourtant mais rien ne se passe.
## Etapes à reproduire (pour les bugs)
je crée bien le fichier custom.json ci dessous

```
    pi@raspberrypi:/var/www/html/plugins/googlecast/core/webradios $ cat custom.json  
    {
        "pomme_dapi": {
                "location": "https://radiopommedapi.ice.infomaniak.ch/radiopommedapi.mp3",
                "title": "Pomme d'Api",
                "image": "https://d3kle7qwymxpcy.cloudfront.net/images/broadcasts/c4/11/41397/1/c300.png"
        }
    }
```
je rentre une nouvelle entrée pour qu'il apparaisse sur mon widget (google mini)

![chrome_2020-05-18_23-38-28](https://user-images.githubusercontent.com/604478/82262223-c937aa00-9960-11ea-98fc-d345043dc154.jpg)

l'entrée apparaît bien
![chrome_2020-05-18_23-40-42](https://user-images.githubusercontent.com/604478/82262338-056b0a80-9961-11ea-9734-afdec22a20e8.jpg)
 
mais aucune radio ne démarre lorsque je choisi cette option.
j'ai relancé le demon et reboot, au cas ou, mais rien

merci de votre retour si j'ai omis un détail de noob^^

## Environnement:
jeedom v4 sur rpi4

**Comment by guirem** [comment]
Il faudrait les logs.

**Comment by Cerzat43** [comment]
@rudak, je viens de faire quelques tests et j'ai trouvé le soucis, il ne faut pas mettre de caractère `'` dans le title.
Les caractères du titre n'étant pas échappés, la chaîne de paramètres est la suivante :
```
app=media|forceplay=2|live=1|value='https://radiopommedapi.ice.infomaniak.ch/radiopommedapi.mp3','audio/mpeg',title:'Pomme d'Api',thumb:'https://d3kle7qwymxpcy.cloudfront.net/images/broadcasts/c4/11/41397/1/c300.png',stream_type:'LIVE'
```
le soucis est donc `title:'Pomme d'Api'`

**Comment by rudak** [comment]
Ooh quel **boulet** je suis.. super merci @Cerzat43 , j'essaie ca rapidement

**Comment by Cerzat43** [comment]
Avec plaisir
Essaie "Pomme d Api" et ce devrait être bon

**Comment by rudak** [comment]
Testé, approuvé, merci 🥇
