### ISSUE TITLE
Blocage lors de l'installation des dépendances

### ISSUE THREAD

**Issue by stefor9393** [guirem/plugin-googlecast#69]
## Description

Bonjour. Je viens d'installer le plug-in et l'installation des dépendances bloque à 20%. Dans la log il demande une confirmation qu'on ne peut pas donner (cf fichier de log ci joint).

[googlecast_update.log](https://github.com/guirem/plugin-googlecast/files/4813310/googlecast_update.log)

## Etapes à reproduire (pour les bugs)

1.
2.
3.
4.

## Environnement:

* **Version Jeedom**: 4.0.58
* **Plateforme**: Jeedom Smart
* **Version du Plugin**: Dernière stable

**Comment by guirem** [comment]
problème de distribution
