### ISSUE TITLE
Jeedom retourne "" pour la commande info player_state

### ISSUE THREAD

**Issue by clempat** [guirem/plugin-googlecast#7]
## Description
Merci pour ce plugin 👍. J'ai un seul petit problème je n'arrive pas à récupérer l'info issue de player_state dans mon scénario car elle est toujours vide.

## Etapes à reproduire (pour les bugs)

1. Avoir Chromecast
2. Lancer un scan sur Jeedom
3. Clicker sur la chromecast sur Jeedom
4. Chercher la commande correspondante à player_state et clicker sur Tester
5. Le resultat de la commande est toujours vide - rien

## Contexte:

J'essai de controller la lumière avec un scénario si un média est lu ou mis en pause.

## Environnement:

* **Version Jeedom**: 3.2.7
* **Plateforme**: Docker (network=host)
* **Version du Plugin**: Stable - 2018-04-27 10:54:11
* **Chromecast**: 1.29.10482
Merci d'avance

Clément

**Comment by guirem** [comment]
Normalement réglé.
A tester dans la beta

**Comment by clempat** [comment]
Merci pour ton travail. J'étais parti en Week-end... Je ne vois pas de version Beta pour le tester. Est-ce normale ?

**Comment by clempat** [comment]
Je n'avais pas vu que je n'avais pas activé les beta. Ce qui est fait maintenant... Et en effet ca marche. 👍 Super merci pour ton plugin.
