### ISSUE TITLE
Deconnexion Google Home dans le plugin

### ISSUE THREAD

**Issue by gaumejeedom** [guirem/plugin-googlecast#76]
Bonjour, 

Je vous fait part d'un problème que je rencontre depuis environs 3/4 jours.
Les groupes d'enceintes Google Home (constitué uniquement de google Home mini) apparaissent Hors ligne aléatoirement puis reviennent en ligne aléatoirement.

Pour résoudre la problème (de manière temporaire) je dois redémarrer le demon et mes groupes d'enceintes réapparaissent en ligne.

Je ne sais pas exactement d'ou vient le problème, j'ai effectuer la dernière mise à jour du plugin ce weekend, je ne sais pas si le problème viens de la ?? 

Je ne vois rien de spécial dans les logs.

En regardant également les versions de mes google Home mini, j'ai pu voir qu'elle n'avait pas toute la même version de firmware. J'en possède 2 GH en version 1.49.222572 et une autre en 1.42.172094

Un ami à également le même problème avec une installation fraiche de jeedom en V4 alors que moi je suis en V3
Nous avons également le même firmware au niveau des google home 2 en 1.49.222572 et une autre en 1.42.172094
Lui contrairement à moi n'as pas de groupe d'enceinte ce sont les google home qui apparaissent hors ligne.

* **Version Jeedom**: 3 et 4 
* **Plateforme**: Debian Strecht sur VM et Debian Strecht sur VMRaspberry
* **Version du Plugin**: 2.16

**Comment by guirem** [comment]
Le problème est-il toujours présent ?
