### ISSUE TITLE
Google Home non détecté si wifi différent des autres

### ISSUE THREAD

**Issue by JeedHome44** [guirem/plugin-googlecast#77]
Bonjour,

Je constate que mon JBL Link qui est mis sur le point d'accès de ma terrasse en wifi 5 GHz n'est pas détecté par Jeedom qui le marque absent.
Pourtant, il est bien présent sur mon routeur OMR avec IP fixe comme les autres Google Home.

Il est donc impossible de mettre des Google Sur différents points d'accès pour les avoir sur Jeedom? Il faut impérativement les mettre sur le même wifi?

* **Version Jeedom**: dernière version
* **Plateforme**: Pi 4B 8Go

**Comment by guirem** [comment]
Ce n'est pas lié au plugin mais à la configuration réseau.
Regarde dans  la configuration de l'AP si tu as des paramétrages pour le mDNS (mulicast DNS). 
Parfois le paramétrage peut apparaitre sous des noms du type broadcast, multicast...
