### ISSUE TITLE
Impossible de démarrer le démon

### ISSUE THREAD

**Issue by pierredeman** [guirem/plugin-googlecast#8]
## Description

Le démon ne veut pas se lancer.

### Détails démon :
- **Status** : NOK
- **Configuration** : OK

### Logs **Googlecast_local** :
[2018-05-29 15:12:30][ERROR] : GLOBAL------Fatal error : 'ConnectionError' object has no attribute 'message'
[2018-05-29 15:12:30][ERROR] : SENDER------Error on send request to jeedom ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused')) retry : 0/3
[2018-05-29 15:12:30][ERROR] : SENDER------Error on send request to jeedom ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused')) retry : 1/3
[2018-05-29 15:12:30][ERROR] : SENDER------Error on send request to jeedom ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused')) retry : 2/3

## Etapes à reproduire (pour les bugs)

1. Installer le plugin
2. Activer le plugin
3. Installer les dépendances
4. Essayer de démarrer le démon

## Environnement:
DIY (mini-pc Ubuntu, Jeedom Docker)

* **Version Jeedom**: 3.2.7
* **Plateforme**: Docker
* **Version du Plugin**: 2018-04-27 10:54:11

**Comment by guirem** [comment]
Bonjour,
beta/stable ?
Nouvelle install ou update?
Que dit le log en 'debug'?

**Comment by pierredeman** [comment]
Bonjour,

- Version stable
- Nouvelle install
- J'attache les logs de googlecast_local au commentaire

[googlecast_local.log](https://github.com/guirem/plugin-googlecast/files/2049097/googlecast_local.log)

**Comment by guirem** [comment]
Docker en mode host ?
Tu peux tenter en changeant le port peut-être.
Que vois tu dans l'onglet configuration > Réseaux > Gestion avancée ?

**Comment by pierredeman** [comment]
Test effectué en exposant le port 55012, aucune différence (logs joints)
[googlecast_local.log](https://github.com/guirem/plugin-googlecast/files/2053642/googlecast_local.log)

En mode host jeedom ne fonctionne plus, aucun moyen de tester donc.

Le bind sur 127.0.0.1 pose peut-être soucis sous docker? pourrait-on binder sur 0.0.0.0?

**Comment by pierredeman** [comment]
Sur ma config docker, le port jeedom est bindé de cette façon : **0.0.0.0:8080->80/tcp**

C'est ce qui pose problème du coup.

**Si mon accès interne est défini sur 192.168.x.x : 8080**
- Jeedom me dit que la configuration interne est OK
- Googlecast n'arrive pas à lancer son Démon

**Si mon accès interne est défini sur 127.0.0.1 : 80**
- Jeedom me dit que la configuration interne est NOK
- Googlecast arrive bien pas à lancer son Démon

Une idée pour régler le soucis?

**Comment by guirem** [comment]
Pexu-tu essayer avec la beta et activer l'option "Configuration spéciale (eg: Docker, VM)" dans la config du plugin?

**Comment by pierredeman** [comment]
Plugin beta activé, j'ai une nouvelle erreur maintenant : 
[googlecast_local.log](https://github.com/guirem/plugin-googlecast/files/2055526/googlecast_local.log)

**Comment by pierredeman** [comment]
Ok, merci.

J'ai réinstallé complètement le plugin et tout a l'air OK avec la case "Configuration spéciale" cochée.

Le plugin n'a cependant pas l'air de détecter mon enceinte **JBL Link 20**.
Je referais un test ce soir sans ma connection VPN et te tiendrais informé.

**Comment by pierredeman** [comment]
Le problème n'est pas le même, mais je confirme que la **JBL Link 20** n'est pas reconnu.
Cependant, le Docker est peut-être aussi la raison de ce soucis.

**Comment by guirem** [comment]
Oui très probablement car ton docker n'est pas sur le même réseau que la chromecast. Tu dois probablement avoir d'autres soucis sur d'autres plugins.
Tu peux tenter de lui assigner une adresse ip du même réseau en installant ce script sur ton host:
[pipework](https://github.com/jpetazzo/pipework).
Puis lancer un script de ce type qui associer une nouvelle ip à ton docker une fois lancé:

```
#!/bin/sh

# Configure this part
DOCKERNAME=mycontainername   # container name
IP=192.168.0.X        # ip I want assigned to my docker
GATEWAY=192.168.0.1     # gateway
ETHERNETNAME=eth0     # host ethernet name for the network
PIPEWORKPATH=/path/to/script/pipework
# --------------------

DOCKERRET=`docker inspect -f {{.State.Running}} $DOCKERNAME`

# Will run script only if ip is not available AND docker is running
if [[ "$DOCKERRET" == "true" ]]   # docker is running
then
    PINGRET=`ping -c 1 $IP &> /dev/null ; echo $?;`
	if [[ $PINGRET -ne 0 ]]   # ip not available
	then
		echo "Assigning IP $IP to docker $DOCKERNAME"
		/bin/sh $PIPEWORKPATH $ETHERNETNAME "$DOCKERNAME" $IP/24@$GATEWAY &> /dev/null
	fi
fi
```

**Comment by pierredeman** [comment]
J'ai corrigé le problème en créant un [Network Docker Macvlan](https://docs.docker.com/network/macvlan/) et en y attachant mon container jeedom.
J'ai ensuite changé la **Configuration > Réseau > Accès interne** pour pointer vers la nouvelle IP de ce réseau.

Merci pour tout.
