### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by bwibwi13** [guirem/plugin-googlecast#86]
## Description
J'essaie de faire un cast d'une page web sur mon Google Nest Hub.
Je rencontre quelques difficultés, donc je regarde les logs et je vois cette erreure: "AttributeError: 'NoneType' object has no attribute 'replace'"

## Etapes à reproduire (pour les bugs)
Je n'ai pas réussi à trouver la vraie cause de ce problème

1.

## Contexte:
En cherchant, je pense que ce sont les lignes 'value = value.replace('h:/', 'http://')' dans googlecast.py qui génèrent ce problème.
Manifestement, quelque chose fait que value est parfois vide.

## Proposition de solution (optionnel):
Dans googlecast.py, ajouter un test pour ne faire le replace que quand value n'est pas None :
                        if value is None:
                            logging.error("ACTION------ Missing value for web|load_url")
                        else:
                            value = value.replace('h:/', 'http://')
                            value = value.replace('hs:/', 'https://')

## Environnement:

* **Version Jeedom**: 4.1.22
* **Plateforme**: Raspberry PI 2
* **Version du Plugin**: 2020-12-24 01:10:04

**Comment by guirem** [comment]
added in v 2.18
